import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Word Wall Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Links
        </h1>
        <section>
          <h2>
            Simple Link
          </h2>
          <Link
            href="simple-link"
          >
            This is a simple link
          </Link>
        </section>
        <section>
          <h2>
            More fancy link
          </h2>
          <Link
            prefetch={false}
            href={{
              pathname: '/[username]',
              query: {
                username: 'maxsonyang'
              }
            }}
          >
            It&apos;s so fancy!
          </Link>
        </section>
      </main>
    </>
  )
}
