import Head from 'next/head'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
// import Loader from '@/components/Loader'
import toast from 'react-hot-toast';

export default function Home() {
  return (
    <>
      <Head>
        <title>Word Wall Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => toast.success('Success!')}>
          Success!
        </button>
      </main>
    </>
  )
}
